### PR TITLE
search

### PR DESCRIPTION
**Pull request by Kinga-parasiewicz**
I deleted noresult and we don't see an error but I think that I did something wrong at the beginning because when you write something we should see movie suggestions in moment if you write matrix, for example and our main page should display popular movies. Tell me what do you think?

### CODE REVIEW

**Comment by izabelanowak** [comment]
Okay, I know what you mean. My suggestion is to give up the DynamicBox and in the search engine, a few seconds after the user finishes typing, instead of popular movies, the search results should be displayed on the main page. What do you think about it?

**Comment by Kinga-parasiewicz** [comment]
I think that my option is better because all websites have option what I wrote about.  
But if you want render items on the main browser we can do this. What do you think Krystian ?

**Comment by izabelanowak** [comment]
Ok, let's wait until @krystian-kazmierczak lets us know what he thinks about it too. Alternatively, you could leave the DynamicBox and display, for example, the first search result in it? Then the MediumTile would be insert into DynamicBox. What do you think about it?

**Comment by krystian-kazmierczak** [comment]
The DynamicBox solution is an interesting addition, but if we have problems with its proper operation, I suggest, like @izabelanowak, for the moment to give up this and display the search results on the main page. This feature can be added later, even after publishing the finished application.

**Pull request closed without merging**
