### PR TITLE
Assets

### PR DESCRIPTION
**Pull request by SzymonRojek**
Hi girls, 

This is my first PR. I have chosen and added assets to our project. 

Also, what do you think about the master branch - maybe it will be better to rename it to the main branch, which is more popular now. I think, it will be better to do it from your site Iza but of course I can do it. I am just afraid that it will be to more complicated switching around between branches and us. Let me know what do you think about it.

Let's keep in touch :D

### CODE REVIEW

**Comment by SzymonRojek** [comment]
I am merging the branches. There is no code to review so I have decided to merge them.

**Comment by izabelanowak** [comment]
Master branch in now renamed to main 😄

**Comment by SzymonRojek** [comment]
That's great! Thanks 👍🏻 😄

**Comment by Kinga-parasiewicz** [comment]
I added normalize to main branch

**Comment by SzymonRojek** [comment]
Thats cool Kinga. Normalize is needed :D I can not imagine our work without it hehe 

aaaa => so we have got our main branch now. It works absolutely fine on my local repo, but do not forget to remove master branch from your repo girls - it is easy peasy => [https://dumbitdude.com/how-to-delete-a-branch-in-visual-studio-code/](url). 

Amazing, now we have got the structure ready for our project! 😸

**Comment by izabelanowak** [comment]
Good point, Szymon. I forgot to delete the master branch from my local repo. Thanks for the instruction 😄

**Pull request merged**
